import { supabase } from '@/integrations/supabase/client';
import { CourseWithVideos } from '@/types/lms';

export const INITIAL_REAL_YOUTUBE_COURSES: CourseWithVideos[] = [
  {
    id: 'course-hsc-physics-mastery',
    title: 'এইচএসসি পদার্থবিজ্ঞান ১ম ও ২য় পত্র কমপ্লিট একাডেমি (HSC Physics)',
    title_en: 'HSC Physics 1st & 2nd Paper Complete Academic Mastery',
    description: 'ভেক্টর, গতিবিদ্যা, নিউটনিয়ান বলবিদ্যা, কাজ-শক্তি-ক্ষমতা, স্থির তড়িৎ ও আধুনিক পদার্থবিজ্ঞানের প্রতিটি অধ্যায়ের বেসিক কনসেপ্ট, সিকিউ এবং বুয়েট-মেডিকেল প্রাক-প্রস্তুতি।',
    description_en: 'Comprehensive HSC Physics covering mechanics, dynamics, gravitation, optics, and electromagnetism.',
    category: 'HSC Science',
    thumbnail_url: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?q=80&w=1200&auto=format&fit=crop',
    price: 3200,
    is_published: true,
    total_classes: '৩২টি লেকচার',
    duration: '২৪+ ঘন্টা',
    learning_outcomes: [
      'পদার্থবিজ্ঞানের প্রতিটি অধ্যায়ের তাত্ত্বিক ভিত্তি ও গাণিতিক সমস্যা সমাধান',
      'বোর্ড পরীক্ষার সৃজনশীল (CQ) ও বহুনির্বাচনী (MCQ) শতভাগ প্রস্তুতি',
      'বুয়েট ও ইঞ্জিনিয়ারিং এডমিশনের প্রাথমিক কনসেপ্ট ক্লিয়ারিং',
      'বিগত ১০ বছরের বোর্ড প্রশ্ন ও শীর্ষ কলেজগুলোর টেস্ট পেপার সমাধান'
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Engr. Tanvir Ahmed (BUET)',
    videos: [
      {
        id: 'vid-phys-1',
        course_id: 'course-hsc-physics-mastery',
        title: 'লেকচার ১: ভেক্টর - ডট ও ক্রস গুণন এবং নদী-নৌকা সমস্যা সমাধান',
        video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
        video_type: 'youtube',
        duration_seconds: 2840,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-phys-2',
        course_id: 'course-hsc-physics-mastery',
        title: 'লেকচার ২: নিউটনিয়ান বলবিদ্যা - রকেট গতি, ভরবেগ ও ব্যাংকিং কোণ',
        video_url: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        video_type: 'youtube',
        duration_seconds: 3100,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-phys-3',
        course_id: 'course-hsc-physics-mastery',
        title: 'লেকচার ৩: কাজ, শক্তি ও ক্ষমতা - কুয়া ও পাম্পের গাণিতিক সমস্যা',
        video_url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
        video_type: 'youtube',
        duration_seconds: 2650,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-phys-4',
        course_id: 'course-hsc-physics-mastery',
        title: 'লেকচার ৪: স্থির তড়িৎ ও তড়িৎ বিভব - গাউসের সূত্র ও ধারক',
        video_url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
        video_type: 'youtube',
        duration_seconds: 2950,
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-hsc-chemistry-mastery',
    title: 'এইচএসসি রসায়ন ১ম ও ২য় পত্র পূর্ণাঙ্গ একাডেমি (HSC Chemistry)',
    title_en: 'HSC Chemistry 1st & 2nd Paper Complete Academic Prep',
    description: 'গুণগত রসায়ন, মৌলের পর্যায়বৃত্ত ধর্ম, রাসায়নিক পরিবর্তন এবং সম্পূর্ণ জৈব রসায়নের ১০০% কনসেপ্ট ক্লিয়ারিং ও বোর্ড সিকিউ মাস্টারক্লাস।',
    description_en: 'In-depth HSC Chemistry course covering periodic properties, chemical changes, and organic chemistry mechanism.',
    category: 'HSC Science',
    thumbnail_url: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=1200&auto=format&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?q=80&w=1600&auto=format&fit=crop',
    price: 2800,
    is_published: true,
    total_classes: '২৮টি লেকচার',
    duration: '২২+ ঘন্টা',
    learning_outcomes: [
      'কোয়ান্টাম সংখ্যা, অরবিটাল সংকরণ ও পর্যায়বৃত্ত ধর্মের নিখুঁত ব্যাখ্যা',
      'জৈব যৌগের নামকরণ, সমাণুতা ও ইলেকট্রোফিলিক-নিউক্লিওফিলিক বিক্রিয়া',
      'তড়িৎ রসায়ন ও জারণ-বিজারণ সমতাকরণের শর্টকাট টেকনিক',
      'বোর্ড পরীক্ষার শতভাগ কমন উপযোগী সৃজনশীল নোট'
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Dr. Sumaiya Farhana (SSMC)',
    videos: [
      {
        id: 'vid-chem-1',
        course_id: 'course-hsc-chemistry-mastery',
        title: 'লেকচার ১: গুণগত রসায়ন - বোর পরমাণু মডেল ও রিডবার্গ ধ্রুবকের অঙ্ক',
        video_url: 'https://www.youtube.com/watch?v=R9_uLILm0qg',
        video_type: 'youtube',
        duration_seconds: 2450,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-chem-2',
        course_id: 'course-hsc-chemistry-mastery',
        title: 'লেকচার ২: রাসায়নিক পরিবর্তন - Kc, Kp নির্ণয় ও লা-শাতেলীয়ার নীতি',
        video_url: 'https://www.youtube.com/watch?v=3z_2H63b6kE',
        video_type: 'youtube',
        duration_seconds: 2900,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-chem-3',
        course_id: 'course-hsc-chemistry-mastery',
        title: 'লেকচার ৩: জৈব রসায়ন - বেনজিন বলয় প্রতিস্থাপন ও ফ্রিডেল-ক্রাফটস বিক্রিয়া',
        video_url: 'https://www.youtube.com/watch?v=VlS3q_oBfSg',
        video_type: 'youtube',
        duration_seconds: 3300,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-hsc-higher-math',
    title: 'এইচএসসি উচ্চতর গণিত ১ম ও ২য় পত্র কমপ্লিট কোর্স (HSC Higher Math)',
    title_en: 'HSC Higher Mathematics Complete Academic Masterclass',
    description: 'ম্যাট্রিক্স, সরলরেখা, বৃত্ত, ত্রিকোণমিতি, অন্তরীকরণ ও যোগজীকরণের এ-টু-জেড কনসেপ্ট ও রিটেন প্রবলেম সলভিং টেকনিক।',
    description_en: 'Master calculus, coordinate geometry, trigonometry, and vectors for HSC higher mathematics.',
    category: 'HSC Science',
    thumbnail_url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1200&auto=format&fit=crop',
    price: 3000,
    is_published: true,
    total_classes: '৩০টি লেকচার',
    duration: '২৬+ ঘন্টা',
    learning_outcomes: [
      'অন্তরীকরণ (Differentiation) ও যোগজীকরণ (Integration) ডিপ কনসেপ্ট',
      'সরলরেখা ও বৃত্তের সমীকরণ বিশ্লেষণের সহজ নিয়মাবলী',
      'ত্রিকোণমিতিক রূপান্তর ও বিপরীত বৃত্তীয় ফাংশনের ট্রিকস',
      'ক্যালকুলেটর হ্যাকস ও বোর্ড পরীক্ষার সিকিউ স্পেশাল মেথড'
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Fahim Shahriar (DU Physics)',
    videos: [
      {
        id: 'vid-hmath-1',
        course_id: 'course-hsc-higher-math',
        title: 'লেকচার ১: ম্যাট্রিক্স ও নির্ণায়ক - ক্র্যামারের নিয়ম ও বিপরীত ম্যাট্রিক্স',
        video_url: 'https://www.youtube.com/watch?v=V7z7BAZdt2M',
        video_type: 'youtube',
        duration_seconds: 2600,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-hmath-2',
        course_id: 'course-hsc-higher-math',
        title: 'লেকচার ২: সরলরেখা - ঢাল, লম্ব দূরত্ব ও সমান্তরাল রেখার সমীকরণ',
        video_url: 'https://www.youtube.com/watch?v=Yp3w_L_gSNE',
        video_type: 'youtube',
        duration_seconds: 2950,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-hmath-3',
        course_id: 'course-hsc-higher-math',
        title: 'লেকচার ৩: ক্যালকুলাস - লিমিট ও পর্যায়ক্রমিক অন্তরীকরণের ম্যাজিক মেথড',
        video_url: 'https://www.youtube.com/watch?v=VArISKLbZfk',
        video_type: 'youtube',
        duration_seconds: 3400,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-ssc-science-bundle',
    title: 'এসএসসি বিজ্ঞান ৯-১০ পূর্ণাঙ্গ প্রস্তুতি কোর্স (SSC Physics, Chem & Math)',
    title_en: 'SSC Science Class 9-10 Comprehensive Foundation Course',
    description: 'নবম ও দশম শ্রেণির বিজ্ঞান বিভাগের পদার্থবিজ্ঞান, রসায়ন, জীববিজ্ঞান ও উচ্চতর গণিতের পূর্ণাঙ্গ সিলেবাস কভারিং ও টেস্ট পেপার সলভিং।',
    description_en: 'Complete foundation course for SSC Science students covering Physics, Chemistry, Biology, and Higher Math.',
    category: 'SSC 9-10',
    thumbnail_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=1200&auto=format&fit=crop',
    price: 2200,
    is_published: true,
    total_classes: '২৪টি লেকচার',
    duration: '১৮+ ঘন্টা',
    learning_outcomes: [
      'এসএসসি পদার্থ ও রসায়নের অধ্যায়ভিত্তিক মৌলিক ভিত্তি তৈরি',
      'উচ্চতর গণিতের জ্যামিতি, বীজগণিত ও সম্ভাবনা সমাধান',
      'বোর্ড পরীক্ষার মডেল টেস্ট ও রিভিশন প্রোগ্রাম',
      'বিজ্ঞান বিভাগে জিপিএ-৫ নিশ্চিতকরণ গাইডলাইন'
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Prantik Saha (RUET)',
    videos: [
      {
        id: 'vid-ssc-1',
        course_id: 'course-ssc-science-bundle',
        title: 'ক্লাস ১: এসএসসি পদার্থবিজ্ঞান - বল, গতি ও শক্তির মৌলিক নীতি',
        video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
        video_type: 'youtube',
        duration_seconds: 2150,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-ssc-2',
        course_id: 'course-ssc-science-bundle',
        title: 'ক্লাস ২: এসএসসি রসায়ন - পদার্থের গঠন ও রাসায়নিক বন্ধন ব্যাখ্যা',
        video_url: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        video_type: 'youtube',
        duration_seconds: 2300,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-gfx-graphic-design',
    title: 'Graphic Design Full Course (Photoshop & Illustrator)',
    title_en: 'Graphic Design Full Course (Photoshop & Illustrator)',
    description: 'GFXMentor (Imran Ali Dina)-এর প্লেলিস্ট থেকে সম্পূর্ণ গ্রাফিক ডিজাইন কোর্স। ফটোশপ, ইলাস্ট্রেটর, টাইপোগ্রাফি, কালার থিওরি এবং রিয়েল-ওয়ার্ল্ড লোগো ও সোশ্যাল মিডিয়া পোস্ট ডিজাইন শিখুন।',
    description_en: 'Complete Graphic Design course from GFXMentor (Imran Ali Dina) playlist. Learn Photoshop, Illustrator, typography, color theory, logo design, and social media post design.',
    category: 'Graphic & Multimedia',
    thumbnail_url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1200&auto=format&fit=crop',
    price: 0,
    is_published: true,
    landing_slug: 'graphic-design',
    total_classes: '৫টি মাস্টারক্লাস',
    duration: '৩+ ঘন্টা',
    learning_outcomes: [
      'ফটোশপ ও ইলাস্ট্রেটরের প্রতিটি প্রয়োজনীয় টুলসের নিখুঁত ব্যবহার',
      'প্রফেশনাল লোগো ডিজাইন, ব্র্যান্ডিং ও সোশ্যাল মিডিয়া ব্যানার তৈরি',
      'কালার থিওরি, টাইপোগ্রাফি ও লেআউট কম্পোজিশন রুলস',
      'ক্লায়েন্ট প্রজেক্ট হ্যান্ডেলিং ও ফ্রিল্যান্সিং গাইডলাইন'
    ],
    modules: [
      {
        id: 'gfx-m1',
        title: 'মডিউল ০১: গ্রাফিক্স ডিজাইন ফান্ডামেন্টালস ও ইন্টারফেস পরিচিতি',
        description: 'ফটোশপ ও ইলাস্ট্রেটর সেটআপ, ওয়ার্কস্পেস কাস্টমাইজেশন ও বেসিক শেপ তৈরি।',
        order_index: 1,
        lessons_count: 2,
        duration: '৪৫ মিনিট',
      },
      {
        id: 'gfx-m2',
        title: 'মডিউল ০২: পেন টুল ও সিলেকশন মাস্টারক্লাস',
        description: 'জটিল ভেক্টর শেপ তৈরি ও নিখুঁত সিলেকশন টেকনিক।',
        order_index: 2,
        lessons_count: 2,
        duration: '১ ঘন্টা',
      },
      {
        id: 'gfx-m3',
        title: 'মডিউল ০৩: টাইপোগ্রাফি ও রিয়েল-লাইফ লোগো ডিজাইন',
        description: 'ফন্ট সিলেকশন নিয়মাবলী, ব্র্যান্ডিং কনসেপ্ট ও কমপ্লিট লোগো প্রজেক্ট।',
        order_index: 3,
        lessons_count: 2,
        duration: '১ ঘন্টা ১৫ মিনিট',
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'GFXMentor (Imran Ali Dina)',
    videos: [
      {
        id: 'vid-gfx-1',
        course_id: 'course-gfx-graphic-design',
        title: 'Class 1 - Introduction to Graphic Design & Interface',
        video_url: 'https://www.youtube.com/watch?v=R9_uLILm0qg',
        video_type: 'youtube',
        duration_seconds: 1122, // 18:42
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-gfx-2',
        course_id: 'course-gfx-graphic-design',
        title: 'Class 2 - Selection Tools & Layers Masterclass',
        video_url: 'https://www.youtube.com/watch?v=3z_2H63b6kE',
        video_type: 'youtube',
        duration_seconds: 1455, // 24:15
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-gfx-3',
        course_id: 'course-gfx-graphic-design',
        title: 'Class 3 - Pen Tool Techniques & Vector Shapes',
        video_url: 'https://www.youtube.com/watch?v=VlS3q_oBfSg',
        video_type: 'youtube',
        duration_seconds: 1870, // 31:10
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-gfx-4',
        course_id: 'course-gfx-graphic-design',
        title: 'Class 4 - Typography & Font Selection Rules',
        video_url: 'https://www.youtube.com/watch?v=0hY7-Gk2q24',
        video_type: 'youtube',
        duration_seconds: 1325, // 22:05
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-gfx-5',
        course_id: 'course-gfx-graphic-design',
        title: 'Class 5 - Logo Design & Branding Project',
        video_url: 'https://www.youtube.com/watch?v=d_H3cM2wW-g',
        video_type: 'youtube',
        duration_seconds: 2140, // 35:40
        order_index: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-web-dev-fullstack',
    title: 'Full Stack Web Development & Programming Masterclass',
    title_en: 'Full Stack Web Development & Programming Masterclass',
    description: 'HTML5, CSS3, JavaScript ES6+, React.js, Tailwind CSS এবং Node.js শেখার জন্য পূর্ণাঙ্গ ওয়েব ডেভেলপমেন্ট প্লেলিস্ট। স্ক্র্যাচ থেকে প্রফেশনাল ফুলস্ট্যাক ওয়েবসাইট তৈরির টিউটোরিয়াল।',
    description_en: 'Complete web development playlist covering HTML5, CSS3, JavaScript ES6+, React.js, Tailwind CSS, and Node.js.',
    category: 'Web & Software',
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop',
    price: 0,
    is_published: true,
    landing_slug: 'web-development',
    total_classes: '৮টি প্রজেক্ট ক্লাস',
    duration: '৫+ ঘন্টা',
    learning_outcomes: [
      'আধুনিক HTML5, CSS3, Flexbox & CSS Grid মাস্টার করা',
      'JavaScript ES6+ এবং ডোম ম্যানিপুলেশনে পরিপূর্ণ দক্ষতা',
      'React.js ও Tailwind CSS দিয়ে রেসপনসিভ ইউজার ইন্টারফেস তৈরি',
      'কমপ্লিট ফুলস্ট্যাক ওয়েবসাইট ডেপ্লয়মেন্ট ও হোস্টিং'
    ],
    modules: [
      {
        id: 'web-m1',
        title: 'মডিউল ০১: ওয়েব ফান্ডামেন্টালস ও আধুনিক HTML5/CSS3',
        description: 'ইন্টারনেট কিভাবে কাজ করে, সেমান্টিক HTML ও রেসপনসিভ সিএসএস লেআউট।',
        order_index: 1,
        lessons_count: 3,
        duration: '১ ঘন্টা ৩০ মিনিট',
      },
      {
        id: 'web-m2',
        title: 'মডিউল ০২: জাভাস্ক্রিপ্ট প্রোগ্রামিং ও রিয়েল-টাইম ইন্টারেক্টিভিটি',
        description: 'জাভাস্ক্রিপ্ট ডাটা স্ট্রাকচার, ফাংশন, ইভেন্টস ও DOM ম্যানিপুলেশন।',
        order_index: 2,
        lessons_count: 3,
        duration: '২ ঘন্টা',
      },
      {
        id: 'web-m3',
        title: 'মডিউল ০৩: React.js ফ্রেমওয়ার্ক ও ফুলস্ট্যাক প্রজেক্ট তৈরি',
        description: 'কম্পোনেন্ট বেসড আর্কিটেকচার, স্টেট ম্যানেজমেন্ট ও লাইভ ডেপ্লয়মেন্ট।',
        order_index: 3,
        lessons_count: 2,
        duration: '১ ঘন্টা ৪৫ মিনিট',
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Sofiullah Ahammad',
    videos: [
      {
        id: 'vid-web-1',
        course_id: 'course-web-dev-fullstack',
        title: 'Lesson 1 - How the Web Works & HTML5 Fundamentals',
        video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
        video_type: 'youtube',
        duration_seconds: 1530, // 25:30
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-web-2',
        course_id: 'course-web-dev-fullstack',
        title: 'Lesson 2 - Modern CSS3 Flexbox & Grid Layouts',
        video_url: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        video_type: 'youtube',
        duration_seconds: 2295, // 38:15
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-web-3',
        course_id: 'course-web-dev-fullstack',
        title: 'Lesson 3 - JavaScript ES6+ Fundamentals & DOM Manipulation',
        video_url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
        video_type: 'youtube',
        duration_seconds: 2720, // 45:20
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-web-4',
        course_id: 'course-web-dev-fullstack',
        title: 'Lesson 4 - React.js Essentials & Component Architecture',
        video_url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
        video_type: 'youtube',
        duration_seconds: 3130, // 52:10
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-web-5',
        course_id: 'course-web-dev-fullstack',
        title: 'Lesson 5 - Building & Deploying Fullstack App',
        video_url: 'https://www.youtube.com/watch?v=w7ejDZ8SWv8',
        video_type: 'youtube',
        duration_seconds: 2460, // 41:00
        order_index: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-photography-masterclass',
    title: 'Digital Photography & Camera Operation Masterclass',
    title_en: 'Digital Photography & Camera Operation Masterclass',
    description: 'ডিজিটাল ক্যামেরা মেকানিজম, অ্যাপারচার, শাটার স্পিড, আইএসও, এক্সপোজার ট্রায়াঙ্গেল, লাইটিং কন্ট্রোল, পোর্ট্রেট এবং ল্যান্ডস্কেপ ফটোগ্রাফির খুঁটিনাটি সম্পূর্ণ বাংলায় শিখুন।',
    description_en: 'Master digital photography, camera controls, aperture, shutter speed, ISO, exposure triangle, and portrait lighting.',
    category: 'Graphic & Multimedia',
    thumbnail_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1200&auto=format&fit=crop',
    price: 0,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Papiya Sultana',
    videos: [
      {
        id: 'vid-photo-1',
        course_id: 'course-photography-masterclass',
        title: 'Class 1 - Understanding Camera Modes & Exposure Triangle',
        video_url: 'https://www.youtube.com/watch?v=V7z7BAZdt2M',
        video_type: 'youtube',
        duration_seconds: 1215, // 20:15
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-photo-2',
        course_id: 'course-photography-masterclass',
        title: 'Class 2 - Aperture, Shutter Speed & ISO Masterclass',
        video_url: 'https://www.youtube.com/watch?v=Yp3w_L_gSNE',
        video_type: 'youtube',
        duration_seconds: 1720, // 28:40
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-photo-3',
        course_id: 'course-photography-masterclass',
        title: 'Class 3 - Composition Rules & Rule of Thirds',
        video_url: 'https://www.youtube.com/watch?v=VArISKLbZfk',
        video_type: 'youtube',
        duration_seconds: 1170, // 19:30
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-photo-4',
        course_id: 'course-photography-masterclass',
        title: 'Class 4 - Outdoor Lighting & Sun Position Control',
        video_url: 'https://www.youtube.com/watch?v=7uC8z4-Gk2Q',
        video_type: 'youtube',
        duration_seconds: 1610, // 26:50
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-videography-editing',
    title: 'Videography & Premiere Pro Video Editing Masterclass',
    title_en: 'Videography & Premiere Pro Video Editing Masterclass',
    description: 'ভিডিওগ্রাফির সিনেমাটিক শ্যুট টেকনিক, ক্যামেরা মুভমেন্ট, লুম্যাট্রি কালার গ্রেডিং, সাউন্ড ডিজাইন এবং এডোবি প্রিমিয়ার প্রো প্রফেশনাল ভিডিও এডিটিং শিখুন।',
    description_en: 'Learn cinematic videography, camera movements, Lumetri color grading, sound design, and Adobe Premiere Pro video editing.',
    category: 'Graphic & Multimedia',
    thumbnail_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?q=80&w=1200&auto=format&fit=crop',
    price: 0,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Prantik Chakraborty',
    videos: [
      {
        id: 'vid-video-1',
        course_id: 'course-videography-editing',
        title: 'Class 1 - Cinematic Videography & Camera Angles',
        video_url: 'https://www.youtube.com/watch?v=O-3Mlj3MQ_Q',
        video_type: 'youtube',
        duration_seconds: 1270, // 21:10
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-video-2',
        course_id: 'course-videography-editing',
        title: 'Class 2 - Adobe Premiere Pro Timeline & Cutting Tools',
        video_url: 'https://www.youtube.com/watch?v=Hls3Tp7JS8E',
        video_type: 'youtube',
        duration_seconds: 2005, // 33:25
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-video-3',
        course_id: 'course-videography-editing',
        title: 'Class 3 - Color Grading & Lumetri Color Workshop',
        video_url: 'https://www.youtube.com/watch?v=9_oBfSgVlSg',
        video_type: 'youtube',
        duration_seconds: 1785, // 29:45
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-video-4',
        course_id: 'course-videography-editing',
        title: 'Class 4 - Audio Editing, SFX & Export Settings',
        video_url: 'https://www.youtube.com/watch?v=8hY7-Gk2q24',
        video_type: 'youtube',
        duration_seconds: 1635, // 27:15
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-admission-engineering',
    title: 'বুয়েট ও ইঞ্জিনিয়ারিং এডমিশন কমপ্লিট প্রস্তুতি কোর্স',
    title_en: 'BUET & Engineering Admission Complete Preparation Course',
    description: 'বুয়েট, কুয়েট, রুয়েট ও চুয়েট ভর্তি পরীক্ষার জন্য পদার্থবিজ্ঞান, রসায়ন ও উচ্চতর গণিতের কনসেপ্ট ক্লিয়ারিং, অ্যাডভান্সড প্রবলেম সলভিং এবং প্রশ্নব্যাংক অ্যানালাইসিস।',
    description_en: 'Comprehensive engineering admission program covering Advanced Physics, Chemistry, and Higher Math with BUET question bank solving.',
    category: 'Admission Prep',
    thumbnail_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=1200&auto=format&fit=crop',
    price: 4500,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Engr. Tanvir Ahmed (BUET)',
    videos: [
      {
        id: 'vid-eng-1',
        course_id: 'course-admission-engineering',
        title: 'লেকচার ১: নিউটনিয়ান বলবিদ্যা - রকেট গতি ও জড়তার ভ্রামক টেকনিক',
        video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
        video_type: 'youtube',
        duration_seconds: 2840,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-eng-2',
        course_id: 'course-admission-engineering',
        title: 'লেকচার ২: ক্যালকুলাস ও ইন্টিগ্রেশনের বুয়েট স্ট্যান্ডার্ড শর্টকাট',
        video_url: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        video_type: 'youtube',
        duration_seconds: 3200,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-eng-3',
        course_id: 'course-admission-engineering',
        title: 'লেকচার ৩: তড়িৎ রসায়ন ও জারণ-বিজারণ সমতাকরণ মাস্টারক্লাস',
        video_url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
        video_type: 'youtube',
        duration_seconds: 2650,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-eng-4',
        course_id: 'course-admission-engineering',
        title: 'লেকচার ৪: ত্রিকোণমিতি ও বিপরীত বৃত্তীয় ফাংশনের ট্রিকস',
        video_url: 'https://www.youtube.com/watch?v=bMknfKXIFA8',
        video_type: 'youtube',
        duration_seconds: 2450,
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-eng-5',
        course_id: 'course-admission-engineering',
        title: 'লেকচার ৫: বুয়েট বিগত ১০ বছরের লিখিত প্রশ্ন সমাধান কর্মশালা',
        video_url: 'https://www.youtube.com/watch?v=w7ejDZ8SWv8',
        video_type: 'youtube',
        duration_seconds: 3600,
        order_index: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-admission-medical',
    title: 'মেডিকেল ও ডেন্টাল এডমিশন স্পেশাল ব্যাচ (Biology & Chemistry)',
    title_en: 'Medical & Dental Admission Special Master Batch',
    description: 'জাতীয় মেডিকেল ও ডেন্টাল ভর্তি পরীক্ষার জন্য জীববিজ্ঞান (উদ্ভিদ ও প্রাণিবিজ্ঞান), রসায়ন এবং পদার্থবিজ্ঞানের ১০০% নির্ভুল এনসিআরটি/বোর্ড বই লাইন-বাই-লাইন বিশ্লেষণ।',
    description_en: 'Targeted Medical preparation covering Botany, Zoology, General Knowledge, and Chemistry with high-yield memory hacks.',
    category: 'Admission Prep',
    thumbnail_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1200&auto=format&fit=crop',
    price: 3800,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Dr. Sajid Hasan (DMC)',
    videos: [
      {
        id: 'vid-med-1',
        course_id: 'course-admission-medical',
        title: 'ক্লাস ১: কোষ ও কোষের গঠন - মেডিকেল স্পেশাল লাইন-বাই-লাইন রিভিশন',
        video_url: 'https://www.youtube.com/watch?v=R9_uLILm0qg',
        video_type: 'youtube',
        duration_seconds: 2750,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-med-2',
        course_id: 'course-admission-medical',
        title: 'ক্লাস ২: মানব শারীরতত্ত্ব: রক্ত ও সংবহনতন্ত্রের কনসেপ্ট ও চার্ট',
        video_url: 'https://www.youtube.com/watch?v=3z_2H63b6kE',
        video_type: 'youtube',
        duration_seconds: 3100,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-med-3',
        course_id: 'course-admission-medical',
        title: 'ক্লাস ৩: জৈব রসায়নের নামকরণ ও মেকানিজম স্পেশাল টেকনিক',
        video_url: 'https://www.youtube.com/watch?v=VlS3q_oBfSg',
        video_type: 'youtube',
        duration_seconds: 2900,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-med-4',
        course_id: 'course-admission-medical',
        title: 'ক্লাস ৪: মেডিকেল ইংরেজি ও সাধারণ জ্ঞান বিগত বছরের ট্রিকস',
        video_url: 'https://www.youtube.com/watch?v=0hY7-Gk2q24',
        video_type: 'youtube',
        duration_seconds: 1980,
        order_index: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-admission-varsity-a',
    title: 'ঢাকা বিশ্ববিদ্যালয় "ক" ইউনিট (Varsity A-Unit) বিজ্ঞান প্রস্তুতি',
    title_en: 'Dhaka University A-Unit Science Admission Masterclass',
    description: 'ঢাবি ক ইউনিট সহ সকল সাধারণ এবং কৃষি বিশ্ববিদ্যালয়ের বিজ্ঞান অনুষদের জন্য পদার্থ, গণিত, রসায়ন ও জীববিজ্ঞানের এমসিকিউ ও রিটেন সমন্বিত স্পেশাল কোর্স।',
    description_en: 'Dhaka University A-Unit admission preparation for Physics, Chemistry, Math, and Biology with written & MCQ practice.',
    category: 'Admission Prep',
    thumbnail_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1200&auto=format&fit=crop',
    price: 3200,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Fahim Shahriar (DU Physics)',
    videos: [
      {
        id: 'vid-du-1',
        course_id: 'course-admission-varsity-a',
        title: 'ক্লাস ১: মহাকর্ষ ও অভিকর্ষ - ঢাবি বিগত ১৫ বছরের প্রশ্ন সমাধান',
        video_url: 'https://www.youtube.com/watch?v=V7z7BAZdt2M',
        video_type: 'youtube',
        duration_seconds: 2310,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-du-2',
        course_id: 'course-admission-varsity-a',
        title: 'ক্লাস ২: ম্যাট্রিক্স, নির্ণায়ক ও সরলরেখার রিটেন টেকনিক',
        video_url: 'https://www.youtube.com/watch?v=Yp3w_L_gSNE',
        video_type: 'youtube',
        duration_seconds: 2780,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-du-3',
        course_id: 'course-admission-varsity-a',
        title: 'ক্লাস ৩: মৌলের পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন',
        video_url: 'https://www.youtube.com/watch?v=VArISKLbZfk',
        video_type: 'youtube',
        duration_seconds: 2120,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-ict-programming',
    title: 'এইচএসসি আইসিটি ও সি-প্রোগ্রামিং পূর্ণাঙ্গ একাডেমি (HSC ICT)',
    title_en: 'HSC ICT & C-Programming Complete Academic Masterclass',
    description: 'এইচএসসি আইসিটির ৩য় অধ্যায় (সংখ্যা পদ্ধতি ও ডিজিটাল লজিক), ৪র্থ অধ্যায় (এইচটিএমএল ও ওয়েব ডিজাইন) এবং ৫ম অধ্যায় (সি-প্রোগ্রামিং ও অ্যালগরিদম) এর ১০০% বোর্ড প্রস্তুতি ও প্র্যাক্টিক্যাল কোডিং।',
    description_en: 'Comprehensive HSC ICT preparation covering Number Systems, Logic Gates, HTML Web Design, and C-Programming.',
    category: 'HSC ICT & Science',
    thumbnail_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1200&auto=format&fit=crop',
    banner_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1600&auto=format&fit=crop',
    price: 2200,
    is_published: true,
    landing_slug: 'hsc-ict-programming',
    total_classes: '২৬+ ক্লাস',
    duration: '১৮+ ঘন্টা',
    learning_outcomes: [
      'সংখ্যা পদ্ধতির রূপান্তর, ২-এর পরিপূরক ও লজিক গেট সরলীকরণ',
      'এইচটিএমএল ট্যাগ, টেবিল ডিজাইন ও ওয়েব পেজ তৈরি',
      'সি-প্রোগ্রামিংয়ের লুপ, কন্ডিশন, অ্যারে ও ফাংশনের রিয়েল কোডিং',
      'এইচএসসি বোর্ড পরীক্ষার সিকিউ ও এমসিকিউ শর্টকাট টেকনিক'
    ],
    modules: [
      {
        id: 'ict-m1',
        title: 'মডিউল ০১: সংখ্যা পদ্ধতি ও ডিজিটাল লজিক গেটস',
        description: 'বাইনারি, অকটাল, হেক্সাডেসিমেল রূপান্তর, বুলিয়ান অ্যালজেব্রা ও সার্বজনীন গেট বাস্তবায়ন।',
        order_index: 1,
        lessons_count: 6,
        duration: '৪ ঘন্টা',
      },
      {
        id: 'ict-m2',
        title: 'মডিউল ০২: এইচটিএমএল ও ওয়েব পেজ ডিজাইন বেসিক্স',
        description: 'এইচটিএমএল বেসিক সিনট্যাক্স, টেবিল, হাইপারলিংক, ইমেজ ও ফর্ম ডিজাইন।',
        order_index: 2,
        lessons_count: 6,
        duration: '৩.৫ ঘন্টা',
      },
      {
        id: 'ict-m3',
        title: 'মডিউল ০৩: অ্যালগরিদম, ফ্লোচার্ট ও সি-প্রোগ্রামিং ফাউন্ডেশন',
        description: 'ডাটা টাইপ, ইনপুট-আউটপুট, if-else ডিসিশন মেকিং ও লুপ স্ট্রাকচার।',
        order_index: 3,
        lessons_count: 8,
        duration: '৫ ঘন্টা',
      },
      {
        id: 'ict-m4',
        title: 'মডিউল ০৪: অ্যারে, ফাংশন ও বোর্ড পরীক্ষার ফাইনাল সিকিউ প্র্যাকটিস',
        description: 'ওয়ান-ডি ও টু-ডি অ্যারে, ইউজার ডিফাইন্ড ফাংশন ও বিগত বছরের বোর্ড প্রশ্ন সমাধান।',
        order_index: 4,
        lessons_count: 6,
        duration: '৪.৫ ঘন্টা',
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Engr. Tahmid Chowdhury (BUET CSE)',
    videos: [
      {
        id: 'vid-ict-1',
        course_id: 'course-ict-programming',
        title: 'লেকচার ১: সংখ্যা পদ্ধতির রূপান্তর ও ২-এর পরিপূরক বিয়োগের সহজ ট্রিকস',
        video_url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
        video_type: 'youtube',
        duration_seconds: 2150,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-ict-2',
        course_id: 'course-ict-programming',
        title: 'লেকচার ২: ডিজিটাল লজিক গেট সরলীকরণ ও সর্বজনীন গেট ডেরিভেশন',
        video_url: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
        video_type: 'youtube',
        duration_seconds: 2420,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-ict-3',
        course_id: 'course-ict-programming',
        title: 'লেকচার ৩: সি-প্রোগ্রামিং শুরু - অ্যালগরিদম, ফ্লোচার্ট ও প্রথম কোড',
        video_url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
        video_type: 'youtube',
        duration_seconds: 2680,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  },
  {
    id: 'course-digital-marketing-seo',
    title: 'ডিজিটাল মার্কেটিং, এসইও ও মেটা এডস মাস্টারি (Freelancing)',
    title_en: 'Digital Marketing, Advanced SEO & Meta Ads Freelancing',
    description: 'সোশ্যাল মিডিয়া মার্কেটিং (Facebook & Instagram Ads), Google Ads, টেকনিক্যাল এসইও, লোকাল এসইও এবং ফাইভার ও আপওয়ার্কে ক্লায়েন্ট পাওয়ার পূর্ণাঙ্গ গাইডলাইন।',
    description_en: 'Master Facebook/Meta Ads, Google Search Ads, Technical SEO, and international freelancing on Upwork & Fiverr.',
    category: 'Freelancing & Marketing',
    thumbnail_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    price: 2000,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    trainer_name: 'Mahbubur Rahman (Top-Rated Freelancer)',
    videos: [
      {
        id: 'vid-mkt-1',
        course_id: 'course-digital-marketing-seo',
        title: 'মডিউল ১: ডিজিটাল মার্কেটিং পরিচিতি ও নিশ রিসার্চ কৌশল',
        video_url: 'https://www.youtube.com/watch?v=O-3Mlj3MQ_Q',
        video_type: 'youtube',
        duration_seconds: 1820,
        order_index: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-mkt-2',
        course_id: 'course-digital-marketing-seo',
        title: 'মডিউল ২: ফেসবুক ও মেটা পিক্সেল সেটআপ এবং হাই-কনভার্টিং এড ক্যাম্পেইন',
        video_url: 'https://www.youtube.com/watch?v=Hls3Tp7JS8E',
        video_type: 'youtube',
        duration_seconds: 2750,
        order_index: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'vid-mkt-3',
        course_id: 'course-digital-marketing-seo',
        title: 'মডিউল ৩: অন-পেজ ও টেকনিক্যাল এসইও অডিট লাইভ প্রজেক্ট',
        video_url: 'https://www.youtube.com/watch?v=9_oBfSgVlSg',
        video_type: 'youtube',
        duration_seconds: 2480,
        order_index: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ]
  }
];

/**
 * Ensures courses and videos are seeded in Supabase database.
 */
export async function seedRealCoursesToDatabase(): Promise<void> {
  try {
    for (const course of INITIAL_REAL_YOUTUBE_COURSES) {
      // 1. Insert/Upsert course
      const { error: courseError } = await supabase.from('courses').upsert({
        id: course.id,
        title: course.title,
        title_en: course.title_en,
        description: course.description,
        description_en: course.description_en,
        category: course.category,
        thumbnail_url: course.thumbnail_url,
        price: course.price,
        is_published: course.is_published,
        trainer_name: course.trainer_name,
        created_at: course.created_at,
        updated_at: course.updated_at,
      }, { onConflict: 'id' });

      if (courseError) {
        console.warn('Course seed note:', courseError);
      }

      // 2. Insert/Upsert videos for course
      for (const video of course.videos) {
        try {
          await supabase.from('videos').upsert({
            id: video.id,
            course_id: video.course_id,
            title: video.title,
            video_url: video.video_url,
            video_type: video.video_type,
            duration_seconds: video.duration_seconds,
            order_index: video.order_index,
            created_at: video.created_at,
            updated_at: video.updated_at,
          }, { onConflict: 'id' });
        } catch (e) { console.warn('Video seed note:', e); }
      }
    }
  } catch (err) {
    console.warn('Seed exception:', err);
  }
}
